services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: prumo
      POSTGRES_PASSWORD: prumo
      POSTGRES_DB: prumo
    ports:
      - "5432:5432"
    volumes:
      - prumo-db:/var/lib/postgresql/data
volumes:
  prumo-db:
